#!/bin/bash

sudo docker run --name demoiselle-eclipse -ti -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v ~/git/docker-eclipse-demoiselle/workspace:/home/developer/workspace marloncarvalho/demoiselle-eclipse
